Updated script exe2iface

diff --git a/exe2iface b/exe2iface
--- a/exe2iface
+++ b/exe2iface
@@ -6,16 +6,16 @@ RELEASE_DATE="14/11/2025"
 AUTHOR="ElSutien"
 
 error () {
-  echo -n "ERROR: "
-  echo "$1" 1>&2
+  echo -e "\033[1;31mERROR: ${1}\033[0m" 1>&2
   shift
-  eval $*
-  return $?
+  if [ $# -gt 0 ]; then
+    eval $*
+    return $?
+  fi
 }
 
 info () {
-  echo -n "INFO: "
-  echo "$1"
+  echo "\033[1;36mINFO: ${1}\033[0m"
 }
 
 
@@ -75,20 +75,21 @@ askYesNo() {
 }
 
 
-#Check if Dev exist
+# FUNCTION Check if Dev exist on system
 # $1 : Dev name
 checkDev () {
   ip link show dev ${1} 2>&1 1>/dev/null || return 1
   return 0
 }
 
-#Check if Dev used DHCP
+# FUNCTION Check if Dev used DHCP to configure
+# $1 : Dev name
 checkDevIsDhcp () {
   ip route show dev ${1} 2>&1 | grep default | grep -q "proto dhcp" || return 1
   return 0
 }
 
-#Get default route for Dev
+# FUNCTION Get default route for Dev
 # $1 : Dev name
 getDefRouteDev () {
   ip route show dev ${1} 2>&1 1>/dev/null || return 1
@@ -97,14 +98,15 @@ getDefRouteDev () {
   return 0
 }
 
-#Get IPs for Dev
-# $1 : Dev name
+# FUNCTION Get IPs of an iface
+# $1 : iface name
+# Stdout : vector of IPs for the iface
 getIpDev () {
-  (set -- $(ip -br -4 a sh dev $1); shift 2; echo "$*")
-  return 0
+  (set -- $(ip -br -4 a sh dev $1) && shift 2 && echo "$*")
+  return $?
 }
 
-
+# FUNCTION Get the default route via for an iface
 # $1 : Dev name
 # $2 : var name to store Default Via IP
 getDefaultViaDev () {
@@ -243,7 +245,7 @@ if askYesNo "Do you want to enable DHCP?" "" y; then
 fi
 
 info "Executing command: ${CMD} ${ATR[@]}"
-eval ip netns exec ${NETNS} ${CMD} ${ATR[@]} || error "Executing command" exit 6
+eval ip netns exec ${NETNS} ${CMD} ${ATR[@]} || error "Executing command"
 
 #Restoring interface
 info "Disabling namespace..."
